[hekad]
maxprocs = 4

# Heka dashboard for internal metrics and time series graphs
[Dashboard]
type = "DashboardOutput"
address = "0.0.0.0:4352"
ticker_interval = 1

[CounterFilter]
message_matcher = 'Type != "heka.counter-output"'
ticker_interval = 1

[PayloadEncoder]

[LogOutput]
message_matcher = 'Type == "heka.counter-output"'
encoder = "PayloadEncoder"

[json_decoder]
type = "SandboxDecoder"
filename = "lua_decoders/json.lua"
    [json_decoder.config]
    type = "journald.json"

[HttpListenInput]
address = "0.0.0.0:8888"
splitter = "TokenSplitter"
decoder = "json_decoder"
synchronous_decode = false

[ESJsonEncoder]
index = "journald-%{2006.01.02}"
es_index_from_timestamp = true
type_name = "syslog"
id = "%{__CURSOR}"
fields = ["Timestamp", "Fields"]

[ElasticSearchOutput]
server = "%ENV[ES_SERVER]"
message_matcher = "Type == 'journald.json'"
encoder = "ESJsonEncoder"
connect_timeout = %ENV[ES_CONNECT_TIMEOUT]
use_buffering = %ENV[ES_USE_BUFFERING]
queue_max_buffer_size = %ENV[ES_MAX_BUFFER_SIZE]
queue_full_action = "%ENV[ES_BUFFER_FULL_ACTION]"
flush_count = %ENV[ES_FLUSH_COUNT]
flush_interval = %ENV[ES_FLUSH_INTERVAL]
